### ISSUE TITLE
Can't checkout repository

### ISSUE THREAD

**Issue by DaFa66** [trongate/trongate-docs#23]
error: invalid path '0090Modules_Within_Modules/0020what_are_parent_and_child_modules?.html'

Need to remove the '?' from the file name

```
DaFa@Aero:/d/xampp/htdocs$ git clone https://github.com/trongate/trongate-docs.git trongate-docs
Cloning into 'trongate-docs'...
remote: Enumerating objects: 1215, done.
remote: Counting objects: 100% (386/386), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 1215 (delta 176), reused 352 (delta 170), pack-reused 829
Receiving objects:  98% (1191/1215), 10.52 MiB | 6.86 MiB/s
Receiving objects: 100% (1215/1215), 13.31 MiB | 7.15 MiB/s, done.
Resolving deltas: 100% (485/485), done.
error: invalid path '0090Modules_Within_Modules/0020what_are_parent_and_child_modules?.html'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by DaFa66** [comment]
Also getting the following on other files with a '?' in the name:
```
DaFa@Aero:/d/xampp/htdocs/trongate-docs [main]*$ git restore --source=HEAD :/
error: invalid path '0090Modules_Within_Modules/0020what_are_parent_and_child_modules?.html'
error: invalid path '0100Template_and_themes/0010what_are_templates?.html'
error: invalid path '0170The_Module_Import_Wizard/0010what_issue_does_the_module_import_wizard_address?.html'
error: invalid path '0180Authorization_and_Authentication/0020what_is_the_objective?.html'
```

**Comment by gavincox** [comment]
Yeah my bad sorry. Working on a Mac and didn't see the issue.

**Comment by trongate** [comment]
Hi Simon.  There's been a little bit of confusion with regards to how we're dealing with strange characters (such as question marks) in the file names.  However, I've sent some information to the others and I'm waiting for them to give this a thumbs up.  

Once we've clarified how to move forward with regards to file names then I'm hoping to continue with the docs.  I too have been getting merge conflicts.   For now, however, I'm just waiting to hear back from Gavin and Balazs.

**Comment by zatikbalazs** [comment]
Hello DaFa, I had the same problem yesterday and submitted a pull request with the fixes. I agree, file names should not have any strange things going on. I'm fine with all lowercase and underscores as David suggested.

**Comment by DaFa66** [comment]
All good guys and your video explanation DC was ultra-clear!  As long as contributors respect these instructions there shouldn't be any issues going forward.
